export const EnumErrors = {
    ROUTING_ERROR: 1,
    INVALID_TYPES_ERROR: 2,
    DATABASE_ERROR: 3,
    CONTROLLER_ERROR: 4,
    INVALID_PARAMS_ERROR: 5,
    INVALID_BODY_ERROR: 6,
    INVALID_PRICE_ERROR: 7,
    INTERNAL_SERVER_ERROR: 8,
};